format: yamanifest
version: 1.0
---
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ice/ice.restart_file
  hashes:
    binhash: a1091dcbadc1d187ddfab567c8c4085b
    md5: f8c4fe8a2ae26f0d98de541c57d2a76b
work/ice/RESTART/ice.restart_file-20141231:
  copy: true
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ice/ice.restart_file-20141231
  hashes:
    binhash: 6cffefb6e5766d7433d521df554e3862
    md5: f8c4fe8a2ae26f0d98de541c57d2a76b
work/ice/RESTART/iced.20150101:
  copy: true
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ice/iced.20150101
  hashes:
    binhash: b0591619e1dd66396e09d1d083b9985b
    md5: 79f9662f59da0025ea4104a1def62c67
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ice/mice.nc
  hashes:
    binhash: 9b4679e06a182eb7880846d942366018
    md5: 45437261c978bb278c8b558798861844
work/ice/RESTART/mice.nc-20141231:
  copy: true
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ice/mice.nc-20141231
  hashes:
    binhash: 5c7c5ae69b74c25099239a47078f150f
    md5: 45437261c978bb278c8b558798861844
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_age.res.nc
  hashes:
    binhash: f2da8c06a6098da9c3d66595bb08f4cb
    md5: d9aee98a69f2a9744d69f649c6aff6a1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a182347b8ff9abcc0d7c12918b48e833
    md5: cd7f89b05ed7cfb27c7810647e27e12a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c666719e16e893e2bcbb8bc877433527
    md5: 4ae44b74832f5bff09408db375f954fe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_density.res.nc
  hashes:
    binhash: 509338045b04ec7c5f0758f9ee62f6be
    md5: bde8334dcb5a0478fcfe04f37701ba08
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e5c00c9347aa9459f2b85ebe828b40e0
    md5: 2361a1f6be321026ccb60e19e80c2590
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dd230aacaba2ef98b5dc9b23cd934d4a
    md5: 89eb34420f699fce66d865aa6263e2f4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4f1a64fe772b0380e9c4146c519d7311
    md5: c0539dd0410eebfa41bf7c21e3038cf6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e1cf7fb65438e58d2e48d3e8971ae4d4
    md5: ed3984aa594b701f46e6c116cff664cb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6167ae9e2bd4dfbc1c2afc1711ea0a59
    md5: df208892a03d95b1b44d93b0937d5c75
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0c6f9d130e8ef62a4edd4166c31f2313
    md5: 37e63e9d42ee2c55a138836137cab64f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_solo.res
  hashes:
    binhash: cbef882ddc998a5a70c5a7a9932feacf
    md5: a9659ba6023940ced1734515d7353bad
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cb1b241ce28d60312f441f9f2fa0fb81
    md5: 5add83197fad12fdb7be8fecf87b6b19
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_thickness.res.nc
  hashes:
    binhash: eabc07b63a7aa93f1accb58ee7444045
    md5: 14398106969e2c0dae0697e53d27ca88
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_tracer.res
  hashes:
    binhash: 240786b13a2b30fc2c8dafbb7b5085d6
    md5: 04437c2bf9c20227214f611c7521da1b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ac11c2c1b52ac9d9e358f893ca086591
    md5: d397fcb8d1769fb823d22f48ba0caa91
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/if69/qo9901/SSP-585-10-re1-ocn-restart-2014/restart_om_vert/restart_filled_om2/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 60cce02e7fb48a842494406a293389b3
    md5: b9f526030d25278467f448fad856c46e
